class_name DamageDatum extends Resource
# This class contains damage data

var shooter:String = ''
var shooter_team:String = ''
var bullet_type:String = ''
var damage_dealt:float = 0.0
var thing_hit:String = ''
var thing_team:String = ''
var friendly_fire:bool
var undamageable_hit:bool
var timed_out:bool
# Use count to consolidate lots of similar
# damage like is generated by laser beam
var count:int = 1


func _init(data:ShootData) -> void:
	shooter = data.shooter_name
	shooter_team = data.shooter_team
	bullet_type = data.bullet_type
	damage_dealt = data.actual_damage
	if data.thing_hit:
		thing_hit = data.thing_hit.get_name()
		# This next bit is indented because you can't
		# check if a thing has an ally_team if it doesn't
		# exist
		if 'ally_team' in data.thing_hit:
			thing_team = data.thing_hit.ally_team
	friendly_fire = shooter_team==thing_team
	undamageable_hit = data.thing_hit and data.actual_damage==0.0
	timed_out = !data.thing_hit


func print_data() -> void:
	print(shooter, ',', shooter_team, ',', str(bullet_type), ',', damage_dealt, ',', \
		thing_hit, ',', thing_team, ',', friendly_fire, ',', \
		undamageable_hit, ',', timed_out, ',', count)


# Check if this DamageDatum is the same as the given
# one. This is used for consolidate_maybe below.
func same_as_except_damage(dat:DamageDatum) -> bool:
	return shooter==dat.shooter and \
		shooter_team==dat.shooter_team and \
		thing_hit==dat.thing_hit and \
		thing_team==dat.thing_team and \
		undamageable_hit==dat.undamageable_hit


# Returns true if consolidation successful, false otherwise.
# I want to consolidate some very similar damage datums,
# such as the constant damage of laser beams.
func consolidate_maybe(dat:DamageDatum) -> bool:
	if same_as_except_damage(dat):
		damage_dealt += dat.damage_dealt
		count += 1
		return true
	else:
		return false
